# Language configuration

[en]
  languageCode = "en"
  languageName = "English"
  weight = 1
  title = "Issuenator"

  [en.params]
    displayName = "EN"
    isoCode = "en"

  [en.params.author]
    name = "Issuenator"
    links = [
      { mastodon = "https://corporaterunaways.social/@issuenator" },
    ]
