# Navigation menus

[[main]]
  name = "Features"
  pageRef = "features"
  weight = 10

[[main]]
  name = "Docs"
  pageRef = "docs"
  weight = 20

[[main]]
  name = "Support"
  pageRef = "support"
  weight = 30

# Footer menu
[[footer]]
  name = "Privacy"
  pageRef = "privacy"
  weight = 10

[[footer]]
  name = "Support"
  pageRef = "support"
  weight = 20

[[footer]]
  name = "Mastodon"
  url = "https://corporaterunaways.social/@issuenator"
  weight = 30
  [footer.params]
    icon = "mastodon"
    showName = false
    target = "_blank"

[[footer]]
  name = "GitHub"
  url = "https://github.com/dacharyc/issuenator-website"
  weight = 40
  [footer.params]
    icon = "github"
    showName = false
    target = "_blank"

[[footer]]
  name = "Email"
  url = "https://issuenator.app/support/"
  weight = 50
  [footer.params]
    icon = "email"
    showName = false

[[footer]]
  name = "Developer's Website"
  url = "https://dacharycarey.com"
  weight = 60
  [footer.params]
    icon = "globe"
    showName = false
    target = "_blank"
